<? $this->pageTitle = "Products"; ?>
<div id="content">
    <!--<pre><? echo var_dump($this->products->toArray()); ?></pre>-->
    <div id="products">
        <? foreach($this->products->toArray() as $product): ?>
            <div class="product">
                <img src="<? echo $product['productImageLarge']?>" alt="Product" width="100" height="100"/> 
            </div>
        <? endforeach; ?>
    </div>
</div>
