<?php

/**
 * Model_Base_Categories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * 
 * @package    Control in Recommender Systems
 * @subpackage Data Access Layer
 * @author     Baruch College - Jarrod Placide-Raymond <jarrod.raymond@baruch.cuny.edu>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Categories extends Doctrine_Record {
    public function setTableDefinition() {
        $this->setTableName('categories');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'notnull' => false,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'length' => null,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }
    
    public function setUp()
    {
        parent::setUp();
        
    }
}
