<?php

/**
 * Model_Base_Products
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sku
 * @property string $productName
 * @property string $productUrl
 * @property decimal $listPrice
 * @property decimal $salePrice
 * @property string $productImageSmall
 * @property string $productImageLarge
 * @property string $category
 * @property string $region
 * @property string $artistName
 * 
 * @package    Control in Recommender Systems
 * @subpackage Data Access Layer
 * @author     Baruch College - Jarrod Placide-Raymond <jarrod.raymond@baruch.cuny.edu>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Products extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('products');
        $this->hasColumn('sku', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('productName', 'string', 91, array(
             'type' => 'string',
             'length' => 91,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('productUrl', 'string', 54, array(
             'type' => 'string',
             'length' => 54,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('listPrice', 'decimal', 8, array(
             'type' => 'decimal',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'scale' => '2',
             ));
        $this->hasColumn('salePrice', 'decimal', 8, array(
             'type' => 'decimal',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'scale' => '2',
             ));
        $this->hasColumn('productImageSmall', 'string', 48, array(
             'type' => 'string',
             'length' => 48,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('productImageLarge', 'string', 48, array(
             'type' => 'string',
             'length' => 48,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('category', 'string', 26, array(
             'type' => 'string',
             'length' => 26,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('region', 'string', 13, array(
             'type' => 'string',
             'length' => 13,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('artistName', 'string', 42, array(
             'type' => 'string',
             'length' => 42,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}