<? echo $this->doctype() ?> <!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
        <title>Baruch College - <? echo $this->pageTitle ?></title>
        
        <meta name="viewport" content="width=device-width">
        <? $this->headLink()->prependStylesheet('/assets/css/style.css') ?>
        <? echo $this->headLink()->appendStylesheet('/assets/css/jquery/jquery-ui.css') ?>
    </head>
<body>
    <header>
        <h1>Baruch Experiment Sample Site</h1>
    </header>
   <? echo $this->layout()->content ?>
   
   <script src="/assets/js/vendor/jquery-1.8.3.min.js"></script>
   <script src="/assets/js/vendor/jqueryui/jquery-ui.js"></script>
   <script src="/assets/js/main.js"></script>
</body>
</html>