<?php

/**
 * Model_Categories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BuzzyGals
 * @subpackage Data Access Layer
 * @author     Baruch College - Jarrod Placide-Raymond <jarrod.raymond@baruch.cuny.edu>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Categories extends Model_Base_Categories
{

}