<?php

/**
 * Model_CategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_CategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_CategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Categories');
    }
}