<?php

/**
 * Model_ProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Products');
    }
}